"use client";

import { useEffect, useState } from "react";
import Button from "@/components/ui/button";
import axios from "axios";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { showToast } from "react-next-toast";

export interface IPost {
  id: string;
  media_type: string;
  media_url: string;
  permalink: string;
  timestamp: Date;
  caption: string;
}

// Function to get the access token using the access code
const getAccessToken = async (accessCode: string) => {
  try {
    const response = await axios.post(
      "https://api.instagram.com/oauth/access_token",
      {
        client_id: process.env.INSTAGRAM_CLIENT_ID,
        client_secret: process.env.INSTAGRAM_CLIENT_ID,
        grant_type: "authorization_code",
        redirect_uri: "https://realply-insta-fb-poc.vercel.app/",
        code: accessCode,
      },
    );
    return response.data.access_token;
  } catch (error) {
    console.error("Error getting access token:", error);
    throw new Error("Failed to get access token");
  }
};

// Function to get data using the access token
const getPhotos = async (accessToken: string) => {
  try {
    const response = await axios.get(
      `https://graph.instagram.com/me/media?fields=id,caption,media_url,timestamp,media_type,permalink&access_token=${accessToken}`,
    );
    return response.data.data;
  } catch (error) {
    console.error("Error fetching data:", error);
    throw new Error("Failed to fetch data");
  }
};

export default function Home() {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Photo Lab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 flex flex-col h-screen items-center justify-center">
        <div className="flex space-x-4 mt-4">
          <Button className="bg-blue-500" onClick={() => signIn("facebook")}>
            Facebook
          </Button>
          <Button className="bg-[#f38e35]" onClick={() => signIn("instagram")}>
            Instagram
          </Button>
        </div>
      </main>
    </>
  );
}
